config/routes.rb
Prueba7::Application.routes.draw do

  resources :presupuesto_mensuals do
    resources :ingreso_presupuesto_mensuals do
      resources :ejecucion_ingresos
    end
    resources :egreso_presupuesto_mensuals do
      resources :ejecucion_egresos
    end
    member do
      get :ejecucion
    end
  end
  
  resources :tipo_de_presupuestos

  resources :items

  resources :forma_de_pago_al_creditos

  resources :forma_de_pago_al_contados

  resources :financiadors

  resources :tipo_de_forma_de_pagos

  resources :monedas

match 'inicio' => 'inicio#index'

match 'sesion' => 'sesion#index'

match 'seguridad' => 'seguridad#index'

root :to => 'seguridad#index'

  resources :rols

  resources :elementos

  resources :seccions

  resources :usuarios

  resources :empresas

end

app/models/moneda.rb
class Moneda < ActiveRecord::Base
validates_presence_of :nombre
validates_uniqueness_of :nombre
validates_presence_of :simbolo
end

app/controllers/monedas_controller.rb
class MonedasController < ApplicationController
before_filter :autenticacion
  # GET /monedas
  # GET /monedas.json
  def index
    @monedas = Moneda.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @monedas }
    end
  end

  # GET /monedas/1
  # GET /monedas/1.json
  def show
    @moneda = Moneda.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @moneda }
    end
  end

  # GET /monedas/new
  # GET /monedas/new.json
  def new
    @moneda = Moneda.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @moneda }
    end
  end

  # GET /monedas/1/edit
  def edit
    @moneda = Moneda.find(params[:id])
  end

  # POST /monedas
  # POST /monedas.json
  def create
    @moneda = Moneda.new(params[:moneda])

    respond_to do |format|
      if @moneda.save
        format.html { redirect_to @moneda, notice: 'Moneda was successfully created.' }
        format.json { render json: @moneda, status: :created, location: @moneda }
      else
        format.html { render action: "new" }
        format.json { render json: @moneda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /monedas/1
  # PUT /monedas/1.json
  def update
    @moneda = Moneda.find(params[:id])

    respond_to do |format|
      if @moneda.update_attributes(params[:moneda])
        format.html { redirect_to @moneda, notice: 'Moneda was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @moneda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monedas/1
  # DELETE /monedas/1.json
  def destroy
    @moneda = Moneda.find(params[:id])
    @moneda.destroy

    respond_to do |format|
      format.html { redirect_to monedas_url }
      format.json { head :ok }
    end
  end
end

app/helpers/monedas_helper.rb
module MonedasHelper
end

app/views/monedas/_form.html.erb
<%= form_for(@moneda) do |f| %>
  <% if @moneda.errors.any? %>
    <div id="error_explanation">
      <h2>No se puede grabar porque no ha pasado la validacion <%= pluralize(@moneda.errors.count, "dato") %>:</h2>
      <ul>
      <% @moneda.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :nombre, :class => :menuNormal1N %><br />
    <%= f.text_field :nombre, :class => :NormalCajaTexto %>
  </div>
  <div class="field">
    <%= f.label :simbolo, :class => :menuNormal1N %><br />
    <%= f.text_field :simbolo, :class => :NormalCajaTexto %>
  </div>
  <div class="actions">
    <%= f.submit :class => :NormalBoton %>
  </div>
<% end %>

app/views/monedas/edit.html.erb
<%= render 'form' %>
<%= link_to :Detalles, @moneda, :class => :menuLink1N %> |
<%= link_to :Regresar, monedas_path, :class => :menuLink1N %>

app/views/monedas/index.html.erb
<table class="grid">
  <tr Class="gridheader">
    <th>Nombre</th>
    <th>Símbolo</th>
    <th colspan=3></th>
  </tr>
<% x=0; @monedas.each do |moneda| ; c = ((x+=1)%2)==0 ? :gridrow : :gridalternatingrow %>
  <tr class=<%=c%>>
    <td><%= moneda.nombre %></td>
    <td><%= moneda.simbolo %></td>
    <td><%= link_to :Detalles, moneda, :class => :menuLink1N %></td>
    <td><%= link_to :Editar, edit_moneda_path(moneda), :class => :menuLink1N %></td>
    <td><%= link_to :Eliminar, moneda, confirm: "\u00bfEsta seguro?", method: :delete, :class => :menuLink1N %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'Crear nueva moneda', new_moneda_path, :class => :menuLink1N %>

app/views/monedas/new.html.erb
<%= render 'form' %>
<%= link_to :Regresar, monedas_path, :class => :menuLink1N %>

app/views/monedas/show.html.erb
<p id="notice"><%= notice %></p>
<p class="menuNormal1N">
  <b>Nombre:</b>
  <%= @moneda.nombre %>
</p>
<p class="menuNormal1N">
  <b>Simbolo:</b>
  <%= @moneda.simbolo %>
</p>
<%= link_to :Editar, edit_moneda_path(@moneda), :class => :menuLink1N %> |
<%= link_to :Regresar, monedas_path, :class => :menuLink1N %> |
<%= link_to 'Crear nueva moneda', new_moneda_path, :class => :menuLink1N %>