config/routes.rb
Prueba7::Application.routes.draw do

  resources :presupuesto_mensuals do
    resources :ingreso_presupuesto_mensuals do
      resources :ejecucion_ingresos
    end
    resources :egreso_presupuesto_mensuals do
      resources :ejecucion_egresos
    end
    member do
      get :ejecucion
    end
  end
  
  resources :tipo_de_presupuestos

  resources :items

  resources :forma_de_pago_al_creditos

  resources :forma_de_pago_al_contados

  resources :financiadors

  resources :tipo_de_forma_de_pagos

  resources :monedas

match 'inicio' => 'inicio#index'

match 'sesion' => 'sesion#index'

match 'seguridad' => 'seguridad#index'

root :to => 'seguridad#index'

  resources :rols

  resources :elementos

  resources :seccions

  resources :usuarios

  resources :empresas

end

app/models/ejecucion_egreso.rb
class EjecucionEgreso < ActiveRecord::Base
  belongs_to :forma_de_pago_al_contado
  belongs_to :forma_de_pago_al_credito
  belongs_to :egreso_presupuesto_mensual
  validates_presence_of :precio
end

app/models/ejecucion_ingreso.rb
class EjecucionIngreso < ActiveRecord::Base
  belongs_to :forma_de_pago_al_contado
  belongs_to :forma_de_pago_al_credito
  belongs_to :ingreso_presupuesto_mensual
  validates_presence_of :precio
end

app/models/elemento.rb
class Elemento < ActiveRecord::Base
  belongs_to :seccion
  has_and_belongs_to_many :rols
  validates_presence_of :nombre
  validates_presence_of :controlador
  validates_presence_of :seccion_id
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
has_many :usuarios, :dependent=>:destroy
has_many :seccions, :dependent=>:destroy
validates_presence_of :nombre
validates_uniqueness_of :nombre
end

app/models/financiador.rb
class Financiador < ActiveRecord::Base
validates_presence_of :nombre
validates_uniqueness_of :nombre
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :forma_de_pago_al_contados
  has_and_belongs_to_many :forma_de_pago_al_creditos
  validates_presence_of :nombre
  validates_uniqueness_of :nombre
end

app/models/moneda.rb
class Moneda < ActiveRecord::Base
validates_presence_of :nombre
validates_uniqueness_of :nombre
validates_presence_of :simbolo
end

app/models/presupuesto_mensual.rb
class PresupuestoMensual < ActiveRecord::Base
  belongs_to :tipo_de_presupuesto
  belongs_to :moneda
  has_many :ingreso_presupuesto_mensuals
  has_many :egreso_presupuesto_mensuals
  validates_presence_of :periodo
  validates_presence_of :moneda_id
  validates_presence_of :tipo_de_presupuesto_id
end

app/models/rol.rb
class Rol < ActiveRecord::Base
	has_and_belongs_to_many :usuarios
	has_and_belongs_to_many :elementos
	validates_presence_of :nombre
	validates_uniqueness_of :nombre
end

app/models/seccion.rb
class Seccion < ActiveRecord::Base
  belongs_to :empresa
  has_many :elementos, :dependent=>:destroy
  validates_presence_of :nombre
  validates_presence_of :empresa_id
  validates_uniqueness_of :nombre, :scope => :empresa_id
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
    belongs_to :empresa
    validates_presence_of :nombreusuario
    validates_presence_of :clave
    validates_presence_of :nombre
    validates_presence_of :apellidopaterno
    validates_presence_of :apellidomaterno
    validates_presence_of :empresa_id
    validates_uniqueness_of :nombreusuario
    has_and_belongs_to_many :rols
    def nombre_completo
        [nombre,apellidopaterno,apellidomaterno].join(" ").strip
    end
end

app/controllers/presupuesto_mensuals_controller.rb
class PresupuestoMensualsController < ApplicationController
before_filter :autenticacion
  # GET /empresas
  # GET /empresas.json
  def index
    @presupuesto_mensuals = PresupuestoMensual.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @presupuesto_mensuals }
    end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @presupuesto_mensual = PresupuestoMensual.find(params[:id])
    @items = Item.includes(:forma_de_pago_al_contados=>:moneda, :forma_de_pago_al_creditos=>:moneda).where(:monedas => {:id => @presupuesto_mensual.moneda})
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @presupuesto_mensual }
    end
  end
  
  # GET /empresas/1/ejecucion
  # GET /empresas/1/ejecucion.json
  def ejecucion
    @presupuesto_mensual = PresupuestoMensual.find(params[:id])
    respond_to do |format|
      format.html # ejecucion.html.erb
      format.json { render json: @presupuesto_mensual }
    end
  end

  # GET /empresas/new
  # GET /empresas/new.json
  def new
    @presupuesto_mensual = PresupuestoMensual.new
    @tipo_de_presupuestos = TipoDePresupuesto.all 
    @monedas = Moneda.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @presupuesto_mensual }
    end
  end

  # GET /empresas/1/edit
  def edit
    @presupuesto_mensual = PresupuestoMensual.find(params[:id])
    @tipo_de_presupuestos = TipoDePresupuesto.all 
    @monedas = Moneda.all
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @presupuesto_mensual = PresupuestoMensual.new(params[:presupuesto_mensual])
    @tipo_de_presupuestos = TipoDePresupuesto.all 
    @monedas = Moneda.all
    
    respond_to do |format|
      if @presupuesto_mensual.save
        format.html { redirect_to @presupuesto_mensual, notice: 'Presupuesto mensual was successfully created.' }
        format.json { render json: @presupuesto_mensual, status: :created, location: @presupuesto_mensual }
      else
        format.html { render action: "new" }
        format.json { render json: @presupuesto_mensual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /empresas/1
  # PUT /empresas/1.json
  def update
    @presupuesto_mensual = PresupuestoMensual.find(params[:id])
    @tipo_de_presupuestos = TipoDePresupuesto.all 
    @monedas = Moneda.all
    
    respond_to do |format|
      if @presupuesto_mensual.update_attributes(params[:empresa])
        format.html { redirect_to @presupuesto_mensual, notice: 'Presupuesto mensual was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @presupuesto_mensual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @presupuesto_mensual = PresupuestoMensual.find(params[:id])
    @presupuesto_mensual.destroy

    respond_to do |format|
      format.html { redirect_to empresas_url }
      format.json { head :ok }
    end
  end
end

app/helpers/elementos_helper.rb
module ElementosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/monedas_helper.rb
module MonedasHelper
end

app/helpers/presupuesto_mensuals_helper.rb
module PresupuestoMensualsHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/seccions_helper.rb
module SeccionsHelper
end

app/helpers/seguridad_helper.rb
module SeguridadHelper
end

app/helpers/sesion_helper.rb
module SesionHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/presupuesto_mensuals/_egreso_presupuesto_mensuals.html.erb
<table class="grid">
  <tr Class="gridheader">
    <th colspan=3>Ejecucion Egresos</th>
  </tr>
  <tr Class="gridheader">
    <th rowspan=2>Item</th>
    <th colspan=2>Ejecucion</th>
  </tr>
  <tr Class="gridheader">
    <th>Montos reales de este item</th>
    <th>Ejecutar pago</th>
  </tr>
<% x=0; @presupuesto_mensual.egreso_presupuesto_mensuals.each do |egreso_presupuesto_mensual| ; c = ((x+=1)%2)==0 ? :gridrow : :gridalternatingrow %>
  <tr class=<%=c%>>
    <td>
      <p class="menuNormal1N">
        <b>Nombre:</b></br>
        <%= egreso_presupuesto_mensual.item.nombre %>
      </p>
      <p class="menuNormal1N">
        <b>Presupuestado:</b></br>
        <%= @presupuesto_mensual.moneda.simbolo %><%= egreso_presupuesto_mensual.precio %>
      </p>
	  <p class="menuNormal1N">
        <b>Diferencia:</b></br>
        <%= @presupuesto_mensual.moneda.simbolo %><%= (egreso_presupuesto_mensual.precio.to_f - egreso_presupuesto_mensual.ejecucion_egresos.collect(&:precio).reduce(:+).to_f).round 2 %>
      </p>
    </td>
    <td>
      <%= render :partial => 'ejecucion_egresos/ejecucion_egresos', :locals => {:egreso_presupuesto_mensual => egreso_presupuesto_mensual} %>
    </td>
    <td>        
      <%= render :partial => 'ejecucion_egresos/form', :locals => {:egreso_presupuesto_mensual => egreso_presupuesto_mensual} %>  
    </td>
  </tr>
<% end %>
</table>

app/views/presupuesto_mensuals/_form.html.erb
<%= form_for(@presupuesto_mensual) do |f| %>
  <% if @presupuesto_mensual.errors.any? %>
    <div id="error_explanation">
      <h2>No se puede grabar porque no ha pasado la validacion <%= pluralize(@presupuesto_mensual.errors.count, "dato") %>:</h2>
      <ul>
      <% @presupuesto_mensual.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :tipo_de_presupuesto_id, :class => :menuNormal1N %><br />
    <%= f.collection_select :tipo_de_presupuesto_id,@tipo_de_presupuestos,:id,:nombre, {:include_blank => "Seleccione valor"}, {:class => :NormalSelect} %>
  </div>
  <div class="field">
    <%= f.label :periodo, :class => :menuNormal1N %><br />
    <%= f.date_select :periodo, {:order => [:day, :month, :year], :default => Date.today, :discard_day => true, :start_year => 2012}, {:class => :NormalSelect} %>
  </div>
  <div class="field">
    <%= f.label :moneda_id, :class => :menuNormal1N %><br />
    <%= f.collection_select :moneda_id,@monedas,:id,:nombre, {:include_blank => "Seleccione valor"}, {:class => :NormalSelect} %>
  </div>
  <div class="actions">
    <%= f.submit :class => :NormalBoton %>
  </div>
<% end %>

app/views/presupuesto_mensuals/_ingreso_presupuesto_mensuals.html.erb
<table class="grid">
  <tr Class="gridheader">
    <th colspan=3>Ejecucion Ingresos</th>
  </tr>
  <tr Class="gridheader">
    <th rowspan=2>Item</th>
    <th colspan=2>Ejecucion</th>
  </tr>
  <tr Class="gridheader">
    <th>Montos reales de este item</th>
    <th>Ejecutar pago</th>
  </tr>
<% x=0; @presupuesto_mensual.ingreso_presupuesto_mensuals.each do |ingreso_presupuesto_mensual| ; c = ((x+=1)%2)==0 ? :gridrow : :gridalternatingrow %>
  <tr class=<%=c%>>
    <td>
      <p class="menuNormal1N">
        <b>Nombre:</b></br>
        <%= ingreso_presupuesto_mensual.item.nombre %>
      </p>
      <p class="menuNormal1N">
        <b>Presupuestado:</b></br>
        <%= @presupuesto_mensual.moneda.simbolo %><%= ingreso_presupuesto_mensual.precio %>
      </p>
	  <p class="menuNormal1N">
        <b>Diferencia:</b></br>
        <%= @presupuesto_mensual.moneda.simbolo %><%= (ingreso_presupuesto_mensual.ejecucion_ingresos.collect(&:precio).reduce(:+).to_f - ingreso_presupuesto_mensual.precio.to_f).round 2 %>
      </p>
    </td>
    <td>
      <%= render :partial => 'ejecucion_ingresos/ejecucion_ingresos', :locals => {:ingreso_presupuesto_mensual => ingreso_presupuesto_mensual} %>
    </td>
    <td>        
      <%= render :partial => 'ejecucion_ingresos/form', :locals => {:ingreso_presupuesto_mensual => ingreso_presupuesto_mensual} %>  
    </td>
  </tr>
<% end %>
</table>

app/views/presupuesto_mensuals/edit.html.erb
<%= render 'form' %>
<%= link_to :Presupuestar, @presupuesto_mensual, :class => :menuLink1N %> |
<%= link_to :Regresar, presupuesto_mensuals_path, :class => :menuLink1N %>

app/views/presupuesto_mensuals/ejecucion.html.erb
<p id="notice"><%= notice %></p>
<p class="menuNormal1N">
  <b>Tipo de presupuesto:</b>
  <%= @presupuesto_mensual.tipo_de_presupuesto.nombre %>
</p>
<p class="menuNormal1N">
  <b>Periodo:</b>
  <%=l @presupuesto_mensual.periodo, :format => :short %>
</p>
<p class="menuNormal1N">
  <b>Moneda:</b>
  <%= @presupuesto_mensual.moneda.nombre %>
</p>
<p class="menuNormal1N">
  <b>Presupuestado ingresos:</b>
  <%= @presupuesto_mensual.ingreso_presupuesto_mensuals.collect(&:precio).reduce(:+).to_f.round 2%>
  <b>Ejecutado ingresos:</b>
  <%= EjecucionIngreso.includes(:ingreso_presupuesto_mensual).where(:ingreso_presupuesto_mensuals => {:presupuesto_mensual_id => @presupuesto_mensual}).collect(&:precio).reduce(:+).to_f.round 2 %>
</p>
<p class="menuNormal1N">
  <b>Presupuestado egresos:</b>
  <%= @presupuesto_mensual.egreso_presupuesto_mensuals.collect(&:precio).reduce(:+).to_f.round 2 %>
  <b>Ejecutado egresos:</b>
  <%= EjecucionEgreso.includes(:egreso_presupuesto_mensual).where(:egreso_presupuesto_mensuals => {:presupuesto_mensual_id => @presupuesto_mensual}).collect(&:precio).reduce(:+).to_f.round 2 %>
</p>
<p class="menuNormal1N">
  <b>Presupuestado Saldo:</b>
  <%= (@presupuesto_mensual.ingreso_presupuesto_mensuals.collect(&:precio).reduce(:+).to_f - @presupuesto_mensual.egreso_presupuesto_mensuals.collect(&:precio).reduce(:+).to_f).round 2 %>
  <b>Ejecutado Saldo:</b>
  <%= (EjecucionIngreso.includes(:ingreso_presupuesto_mensual).where(:ingreso_presupuesto_mensuals => {:presupuesto_mensual_id => @presupuesto_mensual}).collect(&:precio).reduce(:+).to_f - EjecucionEgreso.includes(:egreso_presupuesto_mensual).where(:egreso_presupuesto_mensuals => {:presupuesto_mensual_id => @presupuesto_mensual}).collect(&:precio).reduce(:+).to_f).round 2 %>
</p>
<p class="menuNormal1N">
  <b>Ingresos:</b>
</p>
<%= render 'ingreso_presupuesto_mensuals' %>
<p class="menuNormal1N">
  <b>Egresos:</b>
</p>
<%= render 'egreso_presupuesto_mensuals' %>
<%= link_to :Regresar, presupuesto_mensuals_path, :class => :menuLink1N %> |
<%= link_to "Crear nuevo presupuesto mensual", new_presupuesto_mensual_path, :class => :menuLink1N %>

app/views/presupuesto_mensuals/index.html.erb
<table class="grid">
  <tr Class="gridheader">
    <th>Tipo de presupuesto</th>
    <th>Periodo</th>
    <th>Moneda</th>
    <th colspan=4></th>
  </tr>
<% x=0; @presupuesto_mensuals.each do |presupuesto_mensual| ; c = ((x+=1)%2)==0 ? :gridrow : :gridalternatingrow %>
  <tr class=<%=c%>>
    <td><%= presupuesto_mensual.tipo_de_presupuesto.nombre %></td>
    <td><%= l presupuesto_mensual.periodo, :format => :short %></td>
    <td><%= presupuesto_mensual.moneda.nombre %></td>
    <td><%= link_to :Ejecucion, ejecucion_presupuesto_mensual_path(presupuesto_mensual), :class => :menuLink1N %></td>
    <td><%= link_to :Presupuestar, presupuesto_mensual, :class => :menuLink1N %></td>
    <td><%= link_to :Editar, edit_presupuesto_mensual_path(presupuesto_mensual), :class => :menuLink1N %></td>
    <td><%= link_to :Eliminar, presupuesto_mensual, confirm: "\u00bfEsta seguro?", method: :delete, :class => :menuLink1N %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'Crear nuevo presupuesto mensual', new_presupuesto_mensual_path, :class => :menuLink1N %>

app/views/presupuesto_mensuals/new.html.erb
<%= render 'form' %>
<%= link_to :Regresar, presupuesto_mensuals_path, :class => :menuLink1N %>

app/views/presupuesto_mensuals/show.html.erb
<p id="notice"><%= notice %></p>
<p class="menuNormal1N">
  <b>Tipo de presupuesto:</b>
  <%= @presupuesto_mensual.tipo_de_presupuesto.nombre %>
</p>
<p class="menuNormal1N">
  <b>Periodo:</b>
  <%=l @presupuesto_mensual.periodo, :format => :short %>
</p>
<p class="menuNormal1N">
  <b>Moneda:</b>
  <%= @presupuesto_mensual.moneda.nombre %>
</p>
<p class="menuNormal1N">
  <b>Saldo:</b>
  <%= (@presupuesto_mensual.ingreso_presupuesto_mensuals.collect(&:precio).reduce(:+).to_f - @presupuesto_mensual.egreso_presupuesto_mensuals.collect(&:precio).reduce(:+).to_f).round(2) if 
  @presupuesto_mensual.ingreso_presupuesto_mensuals.exists? || @presupuesto_mensual.egreso_presupuesto_mensuals.exists?%>
</p>
<table class="grid"><tr><td style="vertical-align:top;">
<%= render 'ingreso_presupuesto_mensuals/ingreso_presupuesto_mensual' %>
<%= render 'ingreso_presupuesto_mensuals/form' %>
</td><td style="vertical-align:top;">
<%= render 'egreso_presupuesto_mensuals/egreso_presupuesto_mensual' %>
<%= render 'egreso_presupuesto_mensuals/form' %>
</tr></td></table>
<%= link_to :Editar, edit_presupuesto_mensual_path(@presupuesto_mensual), :class => :menuLink1N %> |
<%= link_to :Regresar, presupuesto_mensuals_path, :class => :menuLink1N %> |
<%= link_to "Crear nuevo presupuesto mensual", new_presupuesto_mensual_path, :class => :menuLink1N %>