config/routes.rb
Prueba7::Application.routes.draw do

  resources :presupuesto_mensuals do
    resources :ingreso_presupuesto_mensuals do
      resources :ejecucion_ingresos
    end
    resources :egreso_presupuesto_mensuals do
      resources :ejecucion_egresos
    end
    member do
      get :ejecucion
    end
  end
  
  resources :tipo_de_presupuestos

  resources :items

  resources :forma_de_pago_al_creditos

  resources :forma_de_pago_al_contados

  resources :financiadors

  resources :tipo_de_forma_de_pagos

  resources :monedas

match 'inicio' => 'inicio#index'

match 'sesion' => 'sesion#index'

match 'seguridad' => 'seguridad#index'

root :to => 'seguridad#index'

  resources :rols

  resources :elementos

  resources :seccions

  resources :usuarios

  resources :empresas

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :forma_de_pago_al_contados
  has_and_belongs_to_many :forma_de_pago_al_creditos
  validates_presence_of :nombre
  validates_uniqueness_of :nombre
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_filter :autenticacion
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new
    @forma_de_pago_al_contado = FormaDePagoAlContado.all
    @forma_de_pago_al_credito = FormaDePagoAlCredito.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
    @forma_de_pago_al_contado = FormaDePagoAlContado.all
    @forma_de_pago_al_credito = FormaDePagoAlCredito.all
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])
    @forma_de_pago_al_contado = FormaDePagoAlContado.all
    @forma_de_pago_al_credito = FormaDePagoAlCredito.all
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])
    @forma_de_pago_al_contado = FormaDePagoAlContado.all
    @forma_de_pago_al_credito = FormaDePagoAlCredito.all
    
    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>No se puede grabar porque no ha pasado la validacion <%= pluralize(@item.errors.count, "dato") %>:</h2>
      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre, :class => :menuNormal1N %><br />
    <%= f.text_field :nombre, :class => :NormalCajaTexto %>
  </div>
  <div class="field">
    <%= f.label :forma_de_pago_al_contado_ids, :class => :menuNormal1N %><br />
    <%= f.collection_select(:forma_de_pago_al_contado_ids, @forma_de_pago_al_contado, :id, :nombre, {:selected => @item.forma_de_pago_al_contado_ids},{:include_blank => "seleccione valor", :multiple => true, :class => :NormalSelect})%>   
  </div>
  <div class="field">
    <%= f.label :forma_de_pago_al_credito_ids, :class => :menuNormal1N %><br />
    <%= f.collection_select(:forma_de_pago_al_credito_ids, @forma_de_pago_al_credito, :id, :nombre, {:selected => @item.forma_de_pago_al_credito_ids},{:include_blank => "seleccione valor", :multiple => true, :class => :NormalSelect})%>   
  </div>
  <div class="actions">
    <%= f.submit :class => :NormalBoton %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= render 'form' %>
<%= link_to :Detalles, @item, :class => :menuLink1N %> |
<%= link_to :Regresar, items_path, :class => :menuLink1N %>

app/views/items/index.html.erb
<table class="grid">
  <tr Class="gridheader">
    <th>Nombre</th>
    <th>Formas de pago al contado</th>
    <th>Formas de pago al credito</th>
    <th colspan=3></th>
  </tr>
<% x=0; @items.each do |item| ; c = ((x+=1)%2)==0 ? :gridrow : :gridalternatingrow %>
  <tr class=<%=c%>>
    <td><%= item.nombre %></td>
    <td><%= t item.forma_de_pago_al_contados.any?.to_s %></td>
    <td><%= t item.forma_de_pago_al_creditos.any?.to_s %></td>
    <td><%= link_to :Detalles, item, :class => :menuLink1N %></td>
    <td><%= link_to :Editar, edit_item_path(item), :class => :menuLink1N %></td>
    <td><%= link_to :Eliminar, item, confirm: "\u00bfEsta seguro?", method: :delete, :class => :menuLink1N %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'Crear nuevo item', new_item_path, :class => :menuLink1N %>

app/views/items/new.html.erb
<%= render 'form' %>
<%= link_to :Regresar, items_path, :class => :menuLink1N %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<p class="menuNormal1N">
  <b>Nombre:</b>
  <%= @item.nombre %>
</p>
<p class="menuNormal1N">
  <b>Forma de pago al contado:</b>
  <%= @item.forma_de_pago_al_contados.collect(&:nombre).join", " %>
</p>
<p class="menuNormal1N">
  <b>Forma de pago al credito:</b>
  <%= @item.forma_de_pago_al_creditos.collect(&:nombre).join", " %>
</p>
<%= link_to :Editar, edit_item_path(@item), :class => :menuLink1N %> |
<%= link_to :Regresar, items_path, :class => :menuLink1N %> |
<%= link_to 'Crear nuevo item', new_item_path, :class => :menuLink1N %>