config/routes.rb
Prueba7::Application.routes.draw do

  resources :presupuesto_mensuals do
    resources :ingreso_presupuesto_mensuals do
      resources :ejecucion_ingresos
    end
    resources :egreso_presupuesto_mensuals do
      resources :ejecucion_egresos
    end
    member do
      get :ejecucion
    end
  end
  
  resources :tipo_de_presupuestos

  resources :items

  resources :forma_de_pago_al_creditos

  resources :forma_de_pago_al_contados

  resources :financiadors

  resources :tipo_de_forma_de_pagos

  resources :monedas

match 'inicio' => 'inicio#index'

match 'sesion' => 'sesion#index'

match 'seguridad' => 'seguridad#index'

root :to => 'seguridad#index'

  resources :rols

  resources :elementos

  resources :seccions

  resources :usuarios

  resources :empresas

end

app/models/ejecucion_egreso.rb
class EjecucionEgreso < ActiveRecord::Base
  belongs_to :forma_de_pago_al_contado
  belongs_to :forma_de_pago_al_credito
  belongs_to :egreso_presupuesto_mensual
  validates_presence_of :precio
end

app/models/ejecucion_ingreso.rb
class EjecucionIngreso < ActiveRecord::Base
  belongs_to :forma_de_pago_al_contado
  belongs_to :forma_de_pago_al_credito
  belongs_to :ingreso_presupuesto_mensual
  validates_presence_of :precio
end

app/models/elemento.rb
class Elemento < ActiveRecord::Base
  belongs_to :seccion
  has_and_belongs_to_many :rols
  validates_presence_of :nombre
  validates_presence_of :controlador
  validates_presence_of :seccion_id
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
has_many :usuarios, :dependent=>:destroy
has_many :seccions, :dependent=>:destroy
validates_presence_of :nombre
validates_uniqueness_of :nombre
end

app/models/financiador.rb
class Financiador < ActiveRecord::Base
validates_presence_of :nombre
validates_uniqueness_of :nombre
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :forma_de_pago_al_contados
  has_and_belongs_to_many :forma_de_pago_al_creditos
  validates_presence_of :nombre
  validates_uniqueness_of :nombre
end

app/models/moneda.rb
class Moneda < ActiveRecord::Base
validates_presence_of :nombre
validates_uniqueness_of :nombre
validates_presence_of :simbolo
end

app/models/rol.rb
class Rol < ActiveRecord::Base
	has_and_belongs_to_many :usuarios
	has_and_belongs_to_many :elementos
	validates_presence_of :nombre
	validates_uniqueness_of :nombre
end

app/models/seccion.rb
class Seccion < ActiveRecord::Base
  belongs_to :empresa
  has_many :elementos, :dependent=>:destroy
  validates_presence_of :nombre
  validates_presence_of :empresa_id
  validates_uniqueness_of :nombre, :scope => :empresa_id
end

app/models/tipo_de_forma_de_pago.rb
class TipoDeFormaDePago < ActiveRecord::Base
validates_presence_of :nombre
validates_uniqueness_of :nombre
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
    belongs_to :empresa
    validates_presence_of :nombreusuario
    validates_presence_of :clave
    validates_presence_of :nombre
    validates_presence_of :apellidopaterno
    validates_presence_of :apellidomaterno
    validates_presence_of :empresa_id
    validates_uniqueness_of :nombreusuario
    has_and_belongs_to_many :rols
    def nombre_completo
        [nombre,apellidopaterno,apellidomaterno].join(" ").strip
    end
end

app/controllers/tipo_de_forma_de_pagos_controller.rb
class TipoDeFormaDePagosController < ApplicationController
before_filter :autenticacion
  # GET /tipo_de_forma_de_pagos
  # GET /tipo_de_forma_de_pagos.json
  def index
    @tipo_de_forma_de_pagos = TipoDeFormaDePago.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tipo_de_forma_de_pagos }
    end
  end

  # GET /tipo_de_forma_de_pagos/1
  # GET /tipo_de_forma_de_pagos/1.json
  def show
    @tipo_de_forma_de_pago = TipoDeFormaDePago.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tipo_de_forma_de_pago }
    end
  end

  # GET /tipo_de_forma_de_pagos/new
  # GET /tipo_de_forma_de_pagos/new.json
  def new
    @tipo_de_forma_de_pago = TipoDeFormaDePago.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tipo_de_forma_de_pago }
    end
  end

  # GET /tipo_de_forma_de_pagos/1/edit
  def edit
    @tipo_de_forma_de_pago = TipoDeFormaDePago.find(params[:id])
  end

  # POST /tipo_de_forma_de_pagos
  # POST /tipo_de_forma_de_pagos.json
  def create
    @tipo_de_forma_de_pago = TipoDeFormaDePago.new(params[:tipo_de_forma_de_pago])

    respond_to do |format|
      if @tipo_de_forma_de_pago.save
        format.html { redirect_to @tipo_de_forma_de_pago, notice: 'Tipo de forma de pago was successfully created.' }
        format.json { render json: @tipo_de_forma_de_pago, status: :created, location: @tipo_de_forma_de_pago }
      else
        format.html { render action: "new" }
        format.json { render json: @tipo_de_forma_de_pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tipo_de_forma_de_pagos/1
  # PUT /tipo_de_forma_de_pagos/1.json
  def update
    @tipo_de_forma_de_pago = TipoDeFormaDePago.find(params[:id])

    respond_to do |format|
      if @tipo_de_forma_de_pago.update_attributes(params[:tipo_de_forma_de_pago])
        format.html { redirect_to @tipo_de_forma_de_pago, notice: 'Tipo de forma de pago was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipo_de_forma_de_pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_de_forma_de_pagos/1
  # DELETE /tipo_de_forma_de_pagos/1.json
  def destroy
    @tipo_de_forma_de_pago = TipoDeFormaDePago.find(params[:id])
    @tipo_de_forma_de_pago.destroy

    respond_to do |format|
      format.html { redirect_to tipo_de_forma_de_pagos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/elementos_helper.rb
module ElementosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/monedas_helper.rb
module MonedasHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/seccions_helper.rb
module SeccionsHelper
end

app/helpers/seguridad_helper.rb
module SeguridadHelper
end

app/helpers/sesion_helper.rb
module SesionHelper
end

app/helpers/tipo_de_forma_de_pagos_helper.rb
module TipoDeFormaDePagosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/tipo_de_forma_de_pagos/_form.html.erb
<%= form_for(@tipo_de_forma_de_pago) do |f| %>
  <% if @tipo_de_forma_de_pago.errors.any? %>
    <div id="error_explanation">
      <h2>No se puede grabar porque no ha pasado la validacion <%= pluralize(@tipo_de_forma_de_pago.errors.count, "dato") %>:</h2>
      <ul>
      <% @tipo_de_forma_de_pago.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre, :class => :menuNormal1N %><br />
    <%= f.text_field :nombre, :class => :NormalCajaTexto %>
  </div>
  <div class="actions">
    <%= f.submit :class => :NormalBoton %>
  </div>
<% end %>

app/views/tipo_de_forma_de_pagos/edit.html.erb
<%= render 'form' %>
<%= link_to :Detalles, @tipo_de_forma_de_pago, :class => :menuLink1N %> |
<%= link_to :Regresar, tipo_de_forma_de_pagos_path, :class => :menuLink1N %>

app/views/tipo_de_forma_de_pagos/index.html.erb
<table class="grid">
  <tr Class="gridheader">
    <th>Nombre</th>
    <th colspan=3></th>
  </tr>
<% x=0; @tipo_de_forma_de_pagos.each do |tipo_de_forma_de_pago| ; c = ((x+=1)%2)==0 ? :gridrow : :gridalternatingrow %>
  <tr class=<%=c%>>
    <td><%= tipo_de_forma_de_pago.nombre %></td>
    <td><%= link_to :Detalles, tipo_de_forma_de_pago, :class => :menuLink1N %></td>
    <td><%= link_to :Editar, edit_tipo_de_forma_de_pago_path(tipo_de_forma_de_pago), :class => :menuLink1N %></td>
    <td><%= link_to :Eliminar, tipo_de_forma_de_pago, confirm: "\u00bfEsta seguro?", method: :delete, :class => :menuLink1N %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'Crear nuevo tipo de forma de pago', new_tipo_de_forma_de_pago_path, :class => :menuLink1N %>

app/views/tipo_de_forma_de_pagos/new.html.erb
<%= render 'form' %>
<%= link_to :Regresar, tipo_de_forma_de_pagos_path, :class => :menuLink1N %>

app/views/tipo_de_forma_de_pagos/show.html.erb
<p id="notice"><%= notice %></p>
<p class="menuNormal1N">
  <b>Nombre:</b>
  <%= @tipo_de_forma_de_pago.nombre %>
</p>
<%= link_to :Editar, edit_tipo_de_forma_de_pago_path(@tipo_de_forma_de_pago), :class => :menuLink1N %> |
<%= link_to :Regresar, tipo_de_forma_de_pagos_path, :class => :menuLink1N %> |
<%= link_to 'Crear nuevo tipo de forma de pago', new_tipo_de_forma_de_pago_path, :class => :menuLink1N %>